### ISSUE TITLE
NPM support

### ISSUE THREAD

**Issue by dmyers** [oyvindkinsey/easyXDM#275]
If you were to add a `package.json` it would be easier for those using NPM.

**Comment by loganvolkers** [comment]
EasyXDM seems more and more like abandonware. For those looking for a modern alternative without the legacy bloat, try Penpal (https://github.com/Aaronius/penpal).

Penpal was originally inspired by (also good) Postmate (https://github.com/dollarshaveclub/postmate) but has a responsive maintainer, has lighter code and has full 2-way RPC.

**Comment by oyvindkinsey** [comment]
@loganvolkers, not abandonware; but there's not been a large demand to actively maintain it due to how browsers have now caught up. I've been going over some PRs lately though.

As to being unresponsive, this has not been intentional.

**Comment by oyvindkinsey** [comment]
@loganvolkers, both those libraries look great, and would probably be a better choice for many looking to easyXDM these days.
You might think of the legacy bloat as bad, but remember that this project has provided this functionality for over 9 years now, did it across a range of challenging browsers, and has needed very little maintenance due to its future proof design.

**Comment by oyvindkinsey** [comment]
@dmyers https://www.npmjs.com/package/easyxdm already provides an NPM shim for easyXDM, and since I can't personally commit to keeping NPM support up-to-date, I'd rather not take on adding this myself. Want to contribute it?

**Comment by loganvolkers** [comment]
Can't say thank you enough. Long time satisfied user here! Has worked great
for years and years.

I probably don't need all the extra polyfilling for my use cases, so i
don't think I'll contribute the npm support.
